sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t ksav/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true ksav/docker-react npm run test