version: '3.8'
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /usr/app/node_modules
            - type: bind
              source: .
              target: /usr/app
        stdin_open: true
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /usr/app/node_modules
            - type: bind
              source: .
              target: /usr/app
        command: ["npm", "run", "test"]